### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by firstnecron** [firstnecron/tt-twitter-interface#1]
**Rendered Template**
- [ ] Matches the sample layout: a header and three columns of data as shown
- [ ] (Extra) Display a new tweet without having to refresh the page

**Dependency Management**
- [ ] Project includes a package.json file containing dependencies to run the project
- [ ] Running 'npm install' installs relevant dependencies

**Server-Side API Access**
- [ ] Correctly uses an API key and secret from Twitter to communicate on the server
- [ ] Application can be authenticated using a config.js file, and contains code allowing a config.js file to be imported into app.js
- [ ] (Extra) Allows users to post a new tweet

**Correct Express Routes**
- [ ] Renders a template with the user's Twitter info using the '/' route
- [ ] (Extra) Add an 'error' route that renders a friendly error page when something goes wrong

**Displays Correct Information**
- [ ] Displays 5 tweets, 5 friends, 5 messages, and username in a Jade/Pug template that roughly matches the mockups
- [ ] (Extra) Displays the user's profile background image as the site header's background
